apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd  # where Argo CD is installed
spec:
  project: default

  source:
    repoURL: http://nexus-nexus-repository-manager.jenkins:8081/repository/helm-repo/
    chart: my-chart                          # Chart name in your Helm repo
    targetRevision: 0.1.250

    #helm:
      #values: |                            # Inline Helm values (optional)
       # image: 
        #  repository: mycompany-registry.com/my-app
        #  tag: 1.2.3
       # replicaCount: 1 

  destination:
    server:  https://kubernetes.default.svc # Default points to current cluster
    namespace: production                    # Target namespace in your cluster

  syncPolicy:
    automated:                             # Optional: auto-sync changes
      prune: true                          # Remove old resources not in new chart
      selfHeal: true                       # Revert manual changes in the cluster
    syncOptions:
      - CreateNamespace=true               # Auto-create namespace if it doesn't exist
